"""Carga, lectores y preprocesamiento para ECG PhysioNet/CinC 2020.

Módulo fachada (fuente de verdad del esquema v2): tras el split de
depuración, el código vive en :mod:`ecg.schema`, :mod:`ecg.signal` y
:mod:`ecg.datasets`; aquí se re-exporta todo para no romper imports.
Sin dependencias de PyTorch.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

from ecg.schema import (
    BANDPASS_HI_HZ,
    BANDPASS_LO_HZ,
    CLASS_DESCRIPTIONS,
    CLASS_DISPLAY_NAMES,
    CLASS_GROUPS_12,
    CLASS_GROUPS_12_V1_LEGACY,
    CLASS_NAMES,
    CODE_TO_CLASS_INDEX,
    CODE_TO_CLASS_NAME,
    DEFAULT_ADC_GAIN,
    DEFAULT_NORM_MODE,
    EXCLUDED_GROUPS,
    LABEL_SCHEMA,
    LEGACY_CLASS_NAMES,
    LEGACY_LABEL_SCHEMA,
    NUM_CLASSES,
    PHYSICAL_CLIP_MV,
    SCORED_27_CODES,
    class_codes_as_strings,
    class_groups_as_records,
    codes_to_12_vector,
    codes_to_vector,
    is_legacy_schema,
    matched_class_names,
    normalize_snomed_code,
    parse_dx_field,
    preprocessing_for_schema,
)
from ecg.signal import (
    NUM_LEADS,
    STANDARD_LEAD_ORDER,
    TARGET_FS,
    WINDOW_LENGTH,
    WINDOW_SECONDS,
    bandpass_filter,
    compute_window_starts,
    fix_length,
    infer_csv_units,
    load_mat_signal,
    load_wfdb_record,
    load_wfdb_record_windows,
    normalize_lead_name,
    normalize_signal,
    normalize_signal_global,
    parse_adc_spec,
    parse_header,
    preprocess_ecg_array,
    preprocess_to_windows,
    read_csv_ecg,
    reorder_leads,
    resample_signal,
    to_physical_units,
)
from ecg.datasets import (
    DEFAULT_DATA_DIR,
    DEFAULT_OUTPUT_DIR,
    REPO_ROOT,
    build_datasets,
    infer_source_db,
    label_distribution,
    main,
    process_split_to_hdf5,
    scan_records,
    source_distribution,
    split_assignments,
    split_summary,
    stratified_multilabel_split,
    write_reports,
)

__all__ = [
    "BANDPASS_HI_HZ",
    "BANDPASS_LO_HZ",
    "CLASS_DESCRIPTIONS",
    "CLASS_DISPLAY_NAMES",
    "CLASS_GROUPS_12",
    "CLASS_GROUPS_12_V1_LEGACY",
    "CLASS_NAMES",
    "CODE_TO_CLASS_INDEX",
    "CODE_TO_CLASS_NAME",
    "DEFAULT_ADC_GAIN",
    "DEFAULT_DATA_DIR",
    "DEFAULT_NORM_MODE",
    "DEFAULT_OUTPUT_DIR",
    "EXCLUDED_GROUPS",
    "LABEL_SCHEMA",
    "LEGACY_CLASS_NAMES",
    "LEGACY_LABEL_SCHEMA",
    "NUM_CLASSES",
    "NUM_LEADS",
    "PHYSICAL_CLIP_MV",
    "REPO_ROOT",
    "SCORED_27_CODES",
    "STANDARD_LEAD_ORDER",
    "TARGET_FS",
    "WINDOW_LENGTH",
    "WINDOW_SECONDS",
    "bandpass_filter",
    "build_datasets",
    "class_codes_as_strings",
    "class_groups_as_records",
    "codes_to_12_vector",
    "codes_to_vector",
    "compute_window_starts",
    "fix_length",
    "infer_csv_units",
    "infer_source_db",
    "is_legacy_schema",
    "label_distribution",
    "load_mat_signal",
    "load_wfdb_record",
    "load_wfdb_record_windows",
    "main",
    "matched_class_names",
    "normalize_lead_name",
    "normalize_signal",
    "normalize_signal_global",
    "normalize_snomed_code",
    "parse_adc_spec",
    "parse_dx_field",
    "parse_header",
    "preprocess_ecg_array",
    "preprocess_to_windows",
    "preprocessing_for_schema",
    "process_split_to_hdf5",
    "read_csv_ecg",
    "reorder_leads",
    "resample_signal",
    "scan_records",
    "source_distribution",
    "split_assignments",
    "split_summary",
    "stratified_multilabel_split",
    "to_physical_units",
    "write_reports",
]


if __name__ == "__main__":
    main()
